import { useState } from 'react';
import { Link } from 'react-router-dom';
import './DemocracyLab.css';

const modules = [
  {
    id: 'election-builder',
    icon: 'how_to_vote',
    title: 'Build-Your-Own Election',
    desc: 'Design constituencies, set term limits, and define voter eligibility in this sandbox simulator.',
    badge: 'Sandbox',
    badgeColor: 'blue',
    difficulty: 'Beginner',
  },
  {
    id: 'electoral-sim',
    icon: 'bar_chart',
    title: 'Electoral Simulator',
    desc: 'Compare First-Past-The-Post vs. Ranked Choice Voting in real-time datasets.',
    badge: 'Popular',
    badgeColor: 'purple',
    difficulty: 'Intermediate',
    features: ['Analyze Proportional Rep', 'Predict Winner Shifts', 'Suppression Heatmaps'],
  },
  {
    id: 'gerry',
    icon: 'map',
    title: 'Gerrymandering Visualizer',
    desc: "See how 'Packing and Cracking' changes the political landscape of a state map.",
    badge: 'Visual',
    badgeColor: 'teal',
    difficulty: 'Intermediate',
    quote: '"The Gerrymandering simulator made complex spatial politics click for my 11th grade class in minutes!"',
    quoteBy: 'Sarah Miller — Civics Dept.',
  },
  {
    id: 'bill-runner',
    icon: 'gavel',
    title: 'Bill Runner',
    desc: 'Can you pass a bill through congress? A fast-paced legislative mini-game.',
    badge: 'Mini-Game',
    badgeColor: 'amber',
    difficulty: 'Advanced',
    features: ['Draft Legislation', 'Navigate Committees', 'Secure Votes'],
  },
  {
    id: 'civicai',
    icon: 'psychology',
    title: 'CivicAI Assistant',
    desc: 'Get instant, non-partisan answers to your civic and voting questions powered by Google Gemini AI.',
    badge: 'AI-Powered',
    badgeColor: 'purple',
    difficulty: 'Beginner',
    features: ['Google Gemini 1.5 Flash', 'Non-partisan Answers', 'Suggested Questions'],
  },
];


const unlocks = [
  { icon: 'emoji_events', label: 'Civic Apprentice', earned: true },
  { icon: 'star', label: 'Electoral Scholar', earned: true },
  { icon: 'workspace_premium', label: 'Democracy Expert', earned: false },
  { icon: 'military_tech', label: 'Gerrymander Buster', earned: false },
];



export default function DemocracyLab() {
  const [activeModule, setActiveModule] = useState(null);

  const [simProgress, setSimProgress] = useState(34);

  const handleDownloadGuide = (e) => {
    e.stopPropagation();
    const content = `
DEMOCRACY LAB: PARTY GUIDE & ELECTORAL RESOURCE
================================================

1. ELECTION RESULTS ANALYSIS
   - Historical trend mapping
   - Seat-to-vote ratio analysis
   - Demographic shift monitoring

2. RALLY & OUTREACH LOGISTICS
   - Permits and crowd safety
   - Messaging and media engagement
   - Volunteer mobilization

3. CAMPAIGN FINANCE (MONEY NEEDED)
   - Minimum threshold: $500,000 for mid-size districts
   - Allocation: 40% Media, 30% Staff, 20% Logistics, 10% Reserves
   - Compliance and reporting standards

4. VOTER REGISTRATION PROCESS
   - Identification requirements
   - Deadline tracking
   - Digital vs. Physical submission paths

5. STRATEGIC COALITION BUILDING
   - Aligning with local advocacy groups
   - Identifying cross-party policy overlaps

Generated by CivicReady Democracy Lab Resource Center.
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'CivicReady_Party_Guide.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="lab-page">
      {/* Hero */}
      <div className="lab-hero">
        <div className="lab-hero-glow" />
        <div className="container">
          <div className="badge badge-purple" style={{ marginBottom: 16 }}>
            <span className="material-icons-round" style={{ fontSize: 12 }}>science</span>
            12k Active Simulations
          </div>
          <h1>Democracy<span className="gradient-text"> Lab</span></h1>
          <p>Master the mechanics of democracy through interactive simulations. Built for future leaders and curious minds.</p>

          <div className="lab-hero-stats">
            <div className="lab-stat card">
              <div className="lab-stat-label">Mastery Level</div>
              <div className="lab-stat-value">Civic Apprentice</div>
            </div>
            <div className="lab-stat card">
              <div className="lab-stat-label">Sim Progress</div>
              <div className="lab-stat-value">{simProgress}%</div>
              <div className="progress-bar" style={{ marginTop: 8 }}>
                <div className="progress-fill" style={{ width: `${simProgress}%` }} />
              </div>
            </div>
            <div className="lab-stat card">
              <div className="lab-stat-label">Impact</div>
              <div className="lab-stat-value" style={{ color: '#34D399' }}>High</div>
            </div>
          </div>


        </div>
      </div>

      <div className="container lab-body">
        <div className="lab-grid">
          {/* Modules */}
          <div className="lab-modules">
            <div className="dash-section-title" style={{ marginBottom: 20 }}>
              <span className="material-icons-round">grid_view</span>
              Simulation Modules
            </div>
            <div className="modules-grid">
              {modules.map(m => (
                <div
                  key={m.id}
                  className={`module-card card ${activeModule === m.id ? 'module-active' : ''}`}
                  onClick={() => setActiveModule(activeModule === m.id ? null : m.id)}
                >
                  <div className="module-header">
                    <div className="module-icon">
                      <span className="material-icons-round">{m.icon}</span>
                    </div>
                    <span className={`badge badge-${m.badgeColor}`}>{m.badge}</span>
                    <span className="module-difficulty">{m.difficulty}</span>
                  </div>
                  <h3>{m.title}</h3>
                  <p>{m.desc}</p>

                  {m.features && (
                    <ul className="module-features">
                      {m.features.map(f => (
                        <li key={f}>
                          <span className="material-icons-round" style={{ color: '#34D399', fontSize: 14 }}>check_circle</span>
                          {f}
                        </li>
                      ))}
                    </ul>
                  )}

                  {m.quote && activeModule === m.id && (
                    <div className="module-quote">
                      <span className="material-icons-round" style={{ color: 'var(--civic-blue-light)', fontSize: 20, marginBottom: 4 }}>format_quote</span>
                      <p>{m.quote}</p>
                      <span className="quote-by">— {m.quoteBy}</span>
                    </div>
                  )}

                  {m.id === 'election-builder' ? (
                    <Link to="/labs/sandbox" className={`btn ${activeModule === m.id ? 'btn-primary' : 'btn-outline'} module-btn`} style={{textDecoration: 'none', textAlign: 'center'}} onClick={(e) => e.stopPropagation()}>
                      <span className="material-icons-round">{activeModule === m.id ? 'play_arrow' : 'arrow_forward'}</span> {activeModule === m.id ? 'Launch Sim' : 'Simulate'}
                    </Link>
                  ) : m.id === 'electoral-sim' ? (
                    <Link to="/labs/electoral-sim" className={`btn ${activeModule === m.id ? 'btn-primary' : 'btn-outline'} module-btn`} style={{textDecoration: 'none', textAlign: 'center'}} onClick={(e) => e.stopPropagation()}>
                      <span className="material-icons-round">{activeModule === m.id ? 'play_arrow' : 'arrow_forward'}</span> {activeModule === m.id ? 'Launch Sim' : 'Simulate'}
                    </Link>
                  ) : m.id === 'gerry' ? (
                    <Link to="/labs/gerrymander" className={`btn ${activeModule === m.id ? 'btn-primary' : 'btn-outline'} module-btn`} style={{textDecoration: 'none', textAlign: 'center'}} onClick={(e) => e.stopPropagation()}>
                      <span className="material-icons-round">{activeModule === m.id ? 'play_arrow' : 'arrow_forward'}</span> {activeModule === m.id ? 'Launch Sim' : 'Simulate'}
                    </Link>
                  ) : m.id === 'bill-runner' ? (
                    <Link to="/labs/bill-runner" className={`btn ${activeModule === m.id ? 'btn-primary' : 'btn-outline'} module-btn`} style={{textDecoration: 'none', textAlign: 'center'}} onClick={(e) => e.stopPropagation()}>
                      <span className="material-icons-round">{activeModule === m.id ? 'play_arrow' : 'arrow_forward'}</span> {activeModule === m.id ? 'Launch Sim' : 'Simulate'}
                    </Link>
                  ) : m.id === 'civicai' ? (
                    <Link to="/labs/civicai" className={`btn ${activeModule === m.id ? 'btn-primary' : 'btn-outline'} module-btn`} style={{textDecoration: 'none', textAlign: 'center'}} onClick={(e) => e.stopPropagation()}>
                      <span className="material-icons-round">{activeModule === m.id ? 'psychology' : 'arrow_forward'}</span> {activeModule === m.id ? 'Ask CivicAI' : 'Chat'}
                    </Link>
                  ) : (
                    <button
                      className={`btn ${activeModule === m.id ? 'btn-primary' : 'btn-outline'} module-btn`}
                      onClick={e => { e.stopPropagation(); setActiveModule(m.id); setSimProgress(p => Math.min(p + 5, 100)); }}
                    >
                      {activeModule === m.id ? (
                        <><span className="material-icons-round">play_arrow</span> Launch Sim</>
                      ) : (
                        <><span className="material-icons-round">arrow_forward</span> Explore</>
                      )}
                    </button>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Sidebar */}
          <div className="lab-sidebar">
            {/* Unlocks */}
            <div className="card">
              <div className="dash-section-title" style={{ marginBottom: 16 }}>
                <span className="material-icons-round" style={{ color: '#FCD34D' }}>stars</span>
                Your Unlocks
              </div>
              <div className="unlocks-list">
                {unlocks.map(u => (
                  <div key={u.label} className={`unlock-item ${u.earned ? 'earned' : 'locked'}`}>
                    <span className="material-icons-round unlock-icon">{u.icon}</span>
                    <span>{u.label}</span>
                    {!u.earned && <span className="material-icons-round" style={{ marginLeft: 'auto', color: 'var(--text-muted)', fontSize: 16 }}>lock</span>}
                  </div>
                ))}
              </div>
            </div>



            {/* Quick Stats */}
            <div className="card">
              <div className="dash-section-title" style={{ marginBottom: 14 }}>
                <span className="material-icons-round">insights</span>
                Platform Impact
              </div>
              {[
                { label: 'Active Simulations', value: '12,841', icon: 'science' },
                { label: 'Educators Using', value: '3,200+', icon: 'school' },
                { label: 'Countries Reached', value: '47', icon: 'public' },
              ].map(s => (
                <div key={s.label} className="impact-row">
                  <span className="material-icons-round" style={{ color: 'var(--civic-purple-light)', fontSize: 16 }}>{s.icon}</span>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{s.label}</div>
                  </div>
                  <div style={{ fontSize: 16, fontWeight: 700, fontFamily: "'Space Grotesk', sans-serif" }}>{s.value}</div>
                </div>
              ))}
            </div>

            {/* Electoral Resource Sidebar Card */}
            <div className="card" style={{ border: '1px solid rgba(37,99,235,0.2)', background: 'linear-gradient(to bottom, var(--bg-card), rgba(37,99,235,0.05))' }}>
              <div className="module-header" style={{ marginBottom: 12 }}>
                <div className="module-icon" style={{ width: 32, height: 32 }}>
                  <span className="material-icons-round" style={{ fontSize: 18 }}>description</span>
                </div>
                <div className="badge badge-blue">PDF Guide</div>
              </div>
              <h3 style={{ fontSize: 16, marginBottom: 8 }}>Electoral Resource</h3>
              <p style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 16 }}>
                The complete Party Guide: Campaign finance, rally logistics, and registration walkthroughs.
              </p>
              <button className="btn btn-outline full-width" onClick={handleDownloadGuide} style={{ justifyContent: 'center' }}>
                <span className="material-icons-round">download</span> View Resource
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
